### ISSUE TITLE
Syntax error in code from local install

### ISSUE THREAD

**Issue by joshnajera** [zetavg/LLaMA-LoRA-Tuner#13]
While installing locally on a  windows machine using W.S.L. and conda, after installing requirements and trying to run `python app.py --help` I get a syntax error.

```
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from llama_lora.ui.main_page import main_page, get_page_title, main_page_custom_css
  File "/mnt/d/LLaMA-LoRA-Tuner/llama_lora/ui/main_page.py", line 5, in <module>
    from .inference_ui import inference_ui
  File "/mnt/d/LLaMA-LoRA-Tuner/llama_lora/ui/inference_ui.py", line 13, in <module>
    from ..lib.csv_logger import CSVLogger
  File "/mnt/d/LLaMA-LoRA-Tuner/llama_lora/lib/csv_logger.py", line 26
    def setup(
    ^
SyntaxError: duplicate argument 'components' in function definition
```

**Comment by zetavg** [comment]
It might be related to the version of Python; what's your `python --version`?

While I don't have a Windows machine to test it, can you try rolling back to version `acb1b11cc4e64c1203c638d7054242fa792852a4` (last update to `csv_logger.py`) or version `9c78439dafa45b77ced10c1eb2f7c2617133e973` (`csv_logger.py` isn't added) and see if the error is still there?

**Comment by joshnajera** [comment]
Python 3.8.16

Swapped to `acb1b11cc4e64c1203c638d7054242fa792852a4 ` and it was able to call --help!     
Though I haven't downloaded the model yet, so I can't test yet.

**Comment by zetavg** [comment]
I discovered that it's because I merged a PR improperly a few hours ago, it should be fixed on the `main` branch now!
