### ISSUE TITLE
App starts but shows Error on both LoRa Model and Prompt Template fields

### ISSUE THREAD

**Issue by andr6** [zetavg/LLaMA-LoRA-Tuner#8]
Tried GColab and local install. Both show the same error . Can't load model or prompt . 

"Select a LoRA model form your data directory, or type in a model name on HF (e.g: tloen/alpaca-lora-7b)." 

Not sure if doing something wrong .

**Comment by andr6** [comment]
Downloaded model with:  python download_base_model.py  --base_model_names=decapoda-research/llama-7b-hf

**Comment by paplorinc** [comment]
Just tried it as well, it was working for me
